apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 31909
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/veerendra2/prometheus-server:latest
        env:
          - name: api
            value: "https://xx.xx.xx.xx"
          - name: username
            value: "admin"
          - name: password
            value: "xxxxxxxx"
        ports:
        - name: web
          containerPort: 9090
